[package]
name = "crunchy-cli-core"
authors = ["Crunchy Labs Maintainers"]
version = "3.0.0-dev.8"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { version = "4.1", features = ["derive", "string"] }
chrono = "0.4"
crunchyroll-rs = { version = "0.3", features = ["dash-stream"] }
ctrlc = "3.2"
dirs = "5.0"
derive_setters = "0.1"
indicatif = "0.17"
lazy_static = "1.4"
log = { version = "0.4", features = ["std"] }
num_cpus = "1.15"
regex = "1.7"
sanitize-filename = "0.4"
serde = "1.0"
serde_json = "1.0"
shlex = "1.1"
signal-hook = "0.3"
tempfile = "3.5"
terminal_size = "0.2"
tokio = { version = "1.26", features = ["macros", "rt-multi-thread", "time"] }
sys-locale = "0.2"

[build-dependencies]
chrono = "0.4"
